//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integration_IROUTE.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integration_IROUTE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT &apos;N&apos; &quot;Sel&quot;,
        ///T0.&quot;DocEntry&quot;, 
        ///T0.&quot;DocNum&quot;,
        ///T0.&quot;FolioPref&quot;,
        ///T0.&quot;FolioNum&quot;,
        ///T0.&quot;CardCode&quot;, 
        ///T0.&quot;CardName&quot;,
        ///T0.&quot;U_EXX_AIIR_EST&quot;,
        ///T0.&quot;DocDate&quot;,
        ///T0.&quot;Comments&quot;, 
        ///&apos;
        ///                                                                                                                                                                                                                                                            &apos; &quot;Mensaje&quot;
        ///FROM ODLN T0 
        ///WHERE &quot;U_EXX_AIIR_EST&quot; IN({0})
        ///ORDER BY T0.&quot;DocDate&quot;, T0.&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ListarGuías {
            get {
                return ResourceManager.GetString("ListarGuías", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///(SELECT &quot;U_EXX_CONF_VALOR&quot; FROM &quot;@EXX_AIIR_CONF&quot; WHERE &quot;Code&quot; = &apos;002&apos;) &quot;URL&quot;,
        ///(SELECT &quot;U_EXX_CONF_VALOR&quot; FROM &quot;@EXX_AIIR_CONF&quot; WHERE &quot;Code&quot; = &apos;003&apos;) &quot;USUARIO&quot;,
        ///(SELECT &quot;U_EXX_CONF_VALOR&quot; FROM &quot;@EXX_AIIR_CONF&quot; WHERE &quot;Code&quot; = &apos;004&apos;) &quot;CLAVE&quot;
        ///FROM DUMMY.
        /// </summary>
        internal static string ObtenerConfiguracion {
            get {
                return ResourceManager.GetString("ObtenerConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT &quot;U_EXX_CONF_VALOR&quot; FROM &quot;@EXX_AIIR_CONF&quot; WHERE &quot;Code&quot; = &apos;001&apos;.
        /// </summary>
        internal static string ObtenerSL {
            get {
                return ResourceManager.GetString("ObtenerSL", resourceCulture);
            }
        }
    }
}
